% -------------------------------------------------------------------
%  Generated by MATLAB on 5-Mar-2017 23:45:35
%  MATLAB version: 8.6.0.267246 (R2015b)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

foci = saveVarsMat.foci; % <189x250 double> too many elements

clear saveVarsMat;
